version: '3.8'

services:
  postgres:
    image: postgres:16.9-alpine
    container_name: costify-postgres
    environment:
      POSTGRES_DB: costify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - costify-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  costify-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: costify-go-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: costify
      DB_SSLMODE: disable
      SERVER_PORT: 8080
      GIN_MODE: release
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - costify-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  costify-network:
    driver: bridge