erDiagram

    ingredients {
        varchar(255) id PK
        varchar(255) name UK
        numeric(10 package_quantity
        numeric(10 package_price
        timestamp without time zone created_at
        timestamp without time zone updated_at
        measurement_unit package_unit
    }

    recipe_ingredients {
        integer id PK
        varchar(255) recipe_id FK
        varchar(255) ingredient_id FK
        numeric(10 quantity
        timestamp without time zone created_at
        measurement_unit unit
    }

    recipes {
        varchar(255) id PK
        varchar(255) name UK
        timestamp without time zone created_at
        timestamp without time zone updated_at
        numeric(10 total_cost
    }

    ingredients ||--o{ recipe_ingredients : "has"
    recipes ||--o{ recipe_ingredients : "has"
