erDiagram

    ingredients {
        varchar(255) id PK
        varchar(255) name UK
        numeric(10_3) package_quantity
        numeric(10_2) package_price
        timestamp_without_time_zone created_at
        timestamp_without_time_zone updated_at
        measurement_unit package_unit
    }

    recipe_ingredients {
        integer id PK
        varchar(255) recipe_id FK
        varchar(255) ingredient_id FK
        numeric(10_3) quantity
        timestamp_without_time_zone created_at
        measurement_unit unit
    }

    recipes {
        varchar(255) id PK
        varchar(255) name UK
        timestamp_without_time_zone created_at
        timestamp_without_time_zone updated_at
        numeric(10_2) total_cost
    }

    ingredients ||--o{ recipe_ingredients : "has"
    recipes ||--o{ recipe_ingredients : "has"
