name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-api:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make test-api TC_HOST=localhost

  test-web:
    name: Web Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make test-web

  build-web:
    name: Web Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make build-web VITE_COSTIFY_API_URL=${{ vars.VITE_COSTIFY_API_URL }}